### ISSUE TITLE
server configuration

### ISSUE THREAD

**Issue by deviant13** [m-byte/Cigar#17] opened 2015-07-04 03:39 UTC
hello, may i ask where can i edit the server configuration. like food mass, spawn numbers etc. btw im using .exe

**Comment by m-byte** [comment] 2015-07-04 08:47
@deviant13 There should be a file named `masterserver.ini` in your Cigar folder. This is, where you can add or remove regions, and things like that. For every server defined there (e.g. if you set `regions` to `{"Home": 2, "Something": 1}`, you would get 3 game servers), the program will create a file named `gameserver#.ini` (i.e. `gameserver1.ini`, `gameserver2.ini`, ...). You can edit those files to edit settings for a server.

There is also another option:
When you start the server, a console opens. You can use this console to edit your server configuration live. It is documented [in `README.md`](https://github.com/m-byte/Cigar#console-commands).

**Comment by deviant13** [comment] 2015-07-04 16:09
thanks. btw about client there's an error on main_out.js. i try to replay eureka's its working but client freezes randomly :(

**Comment by m-byte** [comment] 2015-07-04 17:11
Can you tell me the error message or post a screenshot of it?

**Comment by vram4** [comment] 2015-07-04 17:17
The freezing should have been fixed in the merge.

**Comment by deviant13** [comment] 2015-07-04 19:04
http://prntscr.com/7oszd1

**Comment by m-byte** [comment] 2015-07-04 21:37
Okay. There seems to be some bug in the server. I'll look into this.

**Comment by m-byte** [comment] 2015-07-04 21:37
@deviant13 You are running the exe, right?

**Comment by deviant13** [comment] 2015-07-04 21:38
yes sir

**Comment by m-byte** [comment] 2015-07-04 21:43
If your server is accessible from the internet: would you mind sharing it with me via mail?
irgendwer2@gmail.com

**Comment by m-byte** [comment] 2015-07-05 00:04
I just sent this to you via mail, but since it might be useful to others as well:

The problem is pretty simple: your client is running inside IIS, your server inside node.js and there is no way for the client to access the server.
The easiest solution is to disable IIS and configure the master server to listen on port 80.
If you also need PHP, use a linux server with nginx and then proxy all requests to node.js

**Comment by deviant13** [comment] 2015-07-05 11:05
btw. can you teach me how to make new cigar.exe?

**Comment by m-byte** [comment] 2015-07-08 11:27
The only advantage windows users get from the exe over installing regular node.js (as on any other platform) is that they don't have to install a compiler. To "make a new exe", you'll have to install a compiler anyway.
So it makes more sense for you to install node.js and a compiler ([options are listed in the node-gyp manual](https://github.com/TooTallNate/node-gyp#installation)). Then, you can just follow the installation [instructions for linux](https://github.com/m-byte/Cigar/blob/master/README.md#obtaining-and-using)

**Comment by deviant13** [comment] 2015-07-08 14:25
hello i follow what you said. and im here now.

what's next sir? 
![screenshot_3](https://cloud.githubusercontent.com/assets/13154299/8572635/36a61712-25c0-11e5-81c8-7b2cd0435b31.png)

**Comment by m-byte** [comment] 2015-07-08 14:30
Run `npm start`                                                                                                                                                                                                                                                                                                                                        Gesendet von meinem BlackBerry 10-Smartphone.                                                                                                                                                                                                                Von: deviant13Gesendet: Mittwoch, 8. Juli 2015 16:25An: m-byte/CigarAntwort an: m-byte/CigarCc: m-byteBetreff: Re: [Cigar] server configuration (#17)hello i follow what you said. and im here now.

what's next sir? 


—Reply to this email directly or view it on GitHub.

**Comment by deviant13** [comment] 2015-07-08 14:37
uhm. im trying to make new exe sir

**Comment by m-byte** [comment] 2015-07-15 11:04
@deviant13 As I wrote, you don't need the exe for windows. It is usually easier to follow the instructions above. The exe is only needed for users without Visual Studio installed.

**Closed by m-byte** 2015-07-15 11:04 UTC

**Comment by Niall7459** [comment] 2016-10-15 07:37
@m-byte Why does it create the third server?

Because If i want only two servers it creates a third and that takes up resource usage
